BOOT_SECTOR = 0
SECTOR_SIZE = 512
TOTAL_SECTORS = 256

CLUSTER_SIZE = 1
TOTAL_CLUSTERS = TOTAL_SECTORS // CLUSTER_SIZE

"""
=== pointers ===
"""

RESERVED_SECTOR = 0
FAT_SECTOR = 1
ROOT_DIRECTORY_SECTOR_START = 2
ROOT_DIRECTORY_SECTOR_END = 5
DATA_SECTOR_START = 6

FAT = [0 for _ in range(TOTAL_CLUSTERS)]

DIRECTORY_ENTRY_SIZE = 32
